# This file acts as the base configuration file for the project.
# See configs/template.yaml for an example how to create a deviating configuration file
# By default the config/user.yaml configuration file is used.

model_type: "triple_loss"
note: "overfit_lambda_exploration_config[hyperparamters][train][lambda_semantic]_config[hyperparamters][train][lambda_contours]"
device: "cuda"
resume_training: false
resume_from: 0
wandb: false

subpaths:
    output: "../output"
    data_location: "../HyperSim_Data_extracted"
    train_data: "data/hypersim/paths/train_img_path_extracted.txt"
    val_data: "data/hypersim/paths/val_img_path_extracted.txt"
    load: ""
    pretrained_weights_path: "pretrained_weights"
    logs: "logs"

data_flags:
    # can be concat, onehot, border, semantic_convolution, simplified_onehot
    type: null
    parameters:
        seg_classes: 40
        simplified_onehot_classes: 3
    return_types:
        onehot: false
        border: false
        simplified_onehot: false

hyperparameters:
    train:
        batch_size: 8
        learning_rate: 0.001
        epochs: 20
        weight_decay: 0
        save_every: 5
        lambda_semantic: 1.
        lambda_contours: 1.
    val:
        batch_size: 8
        val_every: 1

transformations:
    resize:
        width: 768
        height: 576
    depth_range:
        min: 0
        max:  15

save_names:
    weights: "weights.pth"
    optimizer: "optimizer.pth"

pretrained_names:
    weights: "weights.pth"
    pretrained_metadata: "weights_object.pickle"

visualize:
    model_path: ""
