# load the base configuration file
extends: "base.yaml"

# change this to a user specfic project root directory
project_root_dir: "/cluster/project/infk/courses/252-0579-00L/group22_semanticMD/semantic_md"

wandb: false
device: "cuda"

subpaths:
    output: "../experiments"
    data_location: "../hypersim/HyperSim_Data_extracted"
    train_data: "data/train_img_path_extracted.txt"
    val_data: "data/val_img_path_extracted.txt"
    load: ""