# load the base configuration file
extends: "euler.yaml"

model_type: "multi_loss"
note: "multiloss_lambda-0.1_sem40_DiceCE-0.5"
wandb: true

data_flags:
    # can be concat, onehot, border, semantic_convolution, simplified_onehote
    type: null

hyperparameters:
    train:
        batch_size: 32
        learning_rate: 0.001
        epochs: 15
        weight_decay: 0
        save_every: 2
        lambda_semantic: 0.1
        depth_loss_type: "L1"
        semantic_loss_type: "Dice_CE" #can be CE, Dice, FTL, Dice_CE, FTL_CE
        weight_lambda: 0.5
        weight_alpha: 0.8
        weight_gamma: 1.5
    val:
        batch_size: 32